export const state = {
  activeDrawer: null,
  backgroundSuspended: false,
  client: null,
  currentChat: null,
  deferredPersistTimer: null,
  historySynced: false,
  identityPanelOpen: false,
  memberCount: 0,
  manualSyncSession: null,
  messages: [],
  messageKeys: new Set(),
  notice: null,
  noticeAnnouncementTimer: null,
  noticeAutoHideTimer: null,
  noticeFadeTimer: null,
  noticeOpen: false,
  openChannelPanelOpen: false,
  panelPresencePort: null,
  pendingLiveMessages: [],
  seenSyncChunkIds: new Set(),
  seenSyncRequestIds: new Set(),
  settings: null,
  stickyNotice: null,
  syncedChatMeta: null,
  unreadCount: 0,
};
